language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
os:
  - linux
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-test.txt
script: pytest
branches:
  only:
    - dev
    - master

