bulker:
  volumes: ['/tmp']
  envvars: ['DISPLAY']
  default_crate_folder: ${HOME}/bulker_crates
  singularity_image_folder: ${HOME}/simages
  container_system: docker
  executable_template: null
  build_template: null
  crates: null
