bulker:
  build_template: templates/docker_build.jinja2
  container_engine: docker
  crates: null
  default_crate_folder: ${HOME}/bulker_crates
  default_namespace: bulker
  envvars:
  - DISPLAY
  executable_template: templates/docker_executable.jinja2
  rcfile: templates/start.sh
  rcfile_strict: templates/start_strict.sh
  registry_url: http://hub.bulker.io/
  shell_path: ${SHELL}
  shell_rc: $HOME/.bashrc
  shell_template: templates/docker_shell.jinja2
  singularity_image_folder: ${HOME}/simages
  volumes:
  - $HOME
